### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by Abraxas3d** [OpenResearchInstitute/pluto_msk#3]
Ubuntu 20.04
Vivado 2022.2

Vivado environment variable set OK

```
(base) abraxas3d@Jacks:~/documentation-friday/pluto_msk/firmware$ which vivado
/tools/Xilinx/Vivado/2022.2/bin/vivado
(base) abraxas3d@Jacks:~/documentation-friday/pluto_msk/firmware$
```

make fails

```
DTC     arch/arm/boot/dts/zynq-pluto-sdr-revc.dtb
make[1]: Leaving directory '/home/abraxas3d/documentation-friday/pluto_msk/firmware/linux'
dtc -q -@ -I dtb -O dts linux/arch/arm/boot/dts/zynq-pluto-sdr-revc.dtb | sed 's/axi {/amba {/g' | dtc -q -@ -I dts -O dtb -o build/zynq-pluto-sdr-revc.dtb
rm -Rf build/sdk
unzip -o build/system_top.xsa system_top.bit -d build
unzip:  cannot find or open build/system_top.xsa, build/system_top.xsa.zip or build/system_top.xsa.ZIP.
make: *** [Makefile:185: build/system_top.bit] Error 9
rm linux/arch/arm/boot/dts/zynq-pluto-sdr-revc.dtb linux/arch/arm/boot/dts/zynq-pluto-sdr.dtb linux/arch/arm/boot/dts/zynq-pluto-sdr-revb.dtb
```

**Comment by Abraxas3d** [comment]
Deleted repository, attempted again, same error. I attempted it again because the install above required a number of dependencies to be installed along the way, and I wanted to make sure that those installs had not caused some sort of problem. 

Here's the error message:

```
make[1]: Leaving directory '/home/abraxas3d/documentation-vancouver/pluto_msk/firmware/linux'
dtc -q -@ -I dtb -O dts linux/arch/arm/boot/dts/zynq-pluto-sdr-revc.dtb | sed 's/axi {/amba {/g' | dtc -q -@ -I dts -O dtb -o build/zynq-pluto-sdr-revc.dtb
rm -Rf build/sdk
unzip -o build/system_top.xsa system_top.bit -d build
unzip:  cannot find or open build/system_top.xsa, build/system_top.xsa.zip or build/system_top.xsa.ZIP.
make: *** [Makefile:185: build/system_top.bit] Error 9
rm linux/arch/arm/boot/dts/zynq-pluto-sdr-revc.dtb linux/arch/arm/boot/dts/zynq-pluto-sdr.dtb linux/arch/arm/boot/dts/zynq-pluto-sdr-revb.dtb

real	47m18.688s
user	99m25.825s
sys	11m14.176s

```

**Comment by MustBeArt** [comment]
This error message arises when the path to the Vivado tools is not specified correctly. The README gives a clue about this, but doesn't provide explicit instructions. It says:

Check if your Vivado path is correct on this line https://github.com/OpenResearchInstitute/pluto_msk/blob/871bd130de0e6d462138bc6d2981b1c65897a0ca/firmware/Makefile#L19 

On that line, you can see that the Makefile assumes the tools are installed in `/opt/Xilinx`. Depending on how the Xilinx tools were installed, that may or may not be true. If the tools are somewhere else, this needs to be fixed before running `make`. This can be done by editing the above line in `Makefile`, but you will have to re-do that edit every time you clone the repo. A better way is to place a symbolic link in `/opt` that points to the actual tools path.

I'll file a pull request to make this more explicit in the README.
